---

- name: Add the Docker public GPG key to the apt repo
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
           state=present

- name: Add the Docker repo to the trusted sources list
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install Docker
  apt: name=docker-ce state=installed