# this role installs jenkins on the server
#add jenkins installer to the list of sources for the packages
#run the commands below to add Jenkins repository to your system… First add the repository key

- name: Install packages and dependencies
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - default-jdk
    - libfontconfig
    - libffi-dev
    - libncurses5-dev

- name: Add the Jenkins public GPG key to the apt repo
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
           state=present

- name: Add Jenkins to the trusted sources list
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install Jenkins server
  apt: name=jenkins state=installed

- name: start jenkins
  systemd:
    name: jenkins
    state: started

- name: enable jenkins
  systemd:
    name: jenkins
    enabled: true
- name: init password jenkin
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: print init password jenkins
  debug:
    var: result.stdout