- name: install necessary packages
  apt:
    update_cache: yes
    name: '{{ item }}'
    state: present
  with_items:
    - awscli
    - nginx
    - python-pip
    - jq
    - default-jre
    - default-jdk